application:
  port: 8080
  interface: "0.0.0.0"
database:
  require_ssl: true
  username: ""
  password: ""
  port: 5432
  host: ""
  schema_name: "ztpir"
email_client:
  base_url: "http://localhost"
  sender_email: "test@ztpir.com"
  authorization_token: "fake-secret"
