[tools]
"cargo:sqlx-cli" = { version = "0.9.0", features = "postgres rustls", default-features = false }
"cargo:bunyan" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-expand" = { version = "latest", channel = "nightly" }
"cargo:cargo-udeps" = { version = "latest", channel = "nightly" }
# this must be _after_ the cargo:* tools to ensure that they take priority over ~/.cargo/bin in the `mise bin-paths`
rust = { version = "stable", components = ["rustfmt", "llvm-tools-preview", "clippy"] }

#TODO: use a task template (or maybe a postgres/sqlx hidden task depends?) to set these only for the tasks that require them
[env]
ZTPIR_CONTAINER_NAME = "${ZTPIR_CONTAINER_NAME:-ztpir}"
ZTPIR_ENVIRONMENT = "${ZTPIR_ENVIRONMENT:-local}"
ZTPIR_PORT = "${ZTPIR_PORT:-8080}"
POSTGRES_CONTAINER_NAME = "${POSTGRES_CONTAINER_NAME:-postgres}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD:-password}"
POSTGRES_PORT = "${POSTGRES_PORT:-5432}"
POSTGRES_SQLX_USER = "${POSTGRES_SQLX_USER:-app}"
POSTGRES_SQLX_PASSWORD = "${POSTGRES_SQLX_PASSWORD:-password}"
POSTGRES_SQLX_DB = "${POSTGRES_SQLX_DB:-ztpir}"
POSTGRES_SQLX_DATABASE_URI = "postgres://${POSTGRES_SQLX_USER}:${POSTGRES_SQLX_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_SQLX_DB}?sslmode=disable"
POSTGRES_USER = "${POSTGRES_USER:-postgres}"

[tasks.app-container-build]
run = 'container build . --tag "${ZTPIR_CONTAINER_NAME}":local'

# TODO: revisit container networking after https://github.com/apple/container/issues/1809 is merged and released
[tasks.app-container-run]
depends = ["app-container-build", "db-postgres-init"]
run = """
#! /usr/bin/env bash
mise app-container-shutdown
container run \
  --publish "${ZTPIR_PORT}":5432 \
  --network ztpir \
  --detach \
  --name "${ZTPIR_CONTAINER_NAME}" \
  ${ZTPIR_CONTAINER_NAME}:local
"""

[tasks.app-container-shutdown]
run = 'container delete --force "${ZTPIR_CONTAINER_NAME}" 2>/dev/null || true'

[tasks.audit]
run = "cargo audit"

[tasks.build]
run = "cargo build"

[tasks.check]
run = "cargo check"

[tasks.clippy]
run = "cargo clippy"

[tasks.coverage]
run = "cargo llvm-cov"

[tasks.db-postgres-add-migration]
usage = '''
arg "<migration_name>"
'''
run = '''
#! /usr/bin/env bash
if [[ ! "${usage_migration_name}" =~ ^[A-Za-z][A-Za-z_]*$ ]]; then
  >&2 echo "Error: migration name must match '^[A-Za-z][A-Za-z_]*$'"
  exit 1
fi
sqlx migrate add "${usage_migration_name}"
'''

#TODO: docker-compose - this is awful
[tasks.db-postgres-init]
depends = ["db-postgres-shutdown"]
run = """
#! /usr/bin/env bash
set -eo pipefail

trap 'mise run db-postgres-shutdown' SIGINT ERR

container run \
  --env POSTGRES_USER=${POSTGRES_USER} \
  --env POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
  --publish "${POSTGRES_PORT}":5432 \
  --network ztpir \
  --detach \
  --name "${POSTGRES_CONTAINER_NAME}" \
  postgres:18 -N 1000

until container exec "${POSTGRES_CONTAINER_NAME}" pg_isready --username="${POSTGRES_USER}" --quiet; do
  >&2 echo "Awaiting postgres startup"
  sleep 1
done

>&2 echo "Postgres startup complete"
>&2 echo "Initializing app db..."

#TODO: migrations, this is also awful
CREATE_USER_QUERY="CREATE USER ${POSTGRES_SQLX_USER} WITH PASSWORD '${POSTGRES_SQLX_PASSWORD}';"
GRANT_QUERY="ALTER USER ${POSTGRES_SQLX_USER} CREATEDB;"
container exec "${POSTGRES_CONTAINER_NAME}" psql -U "${POSTGRES_USER}" -c "${CREATE_USER_QUERY} ${GRANT_QUERY}"

sqlx database create -D "${POSTGRES_SQLX_DATABASE_URI}"
sqlx migrate run -D "${POSTGRES_SQLX_DATABASE_URI}"
cargo sqlx prepare -D "${POSTGRES_SQLX_DATABASE_URI}" --all -- --all-targets

>&2 echo "Postgres is available on port ${POSTGRES_PORT}"
>&2 echo "Connection String:"
>&2 echo "${POSTGRES_SQLX_DATABASE_URI}"
"""

[tasks.db-postgres-migrate]
run = 'sqlx migrate run -D "${POSTGRES_SQLX_DATABASE_URI}"'

[tasks.db-postgres-shutdown]
run = 'container delete --force "${POSTGRES_CONTAINER_NAME}" 2>/dev/null || true'

[tasks.fmt]
run = "cargo fmt"

[tasks.setup]
run = "rustup toolchain install nightly --allow-downgrade"

[tasks.test]
depends = ["db-postgres-init"]
run = "TEST_LOG=true cargo test | bunyan"
depends_post = ["db-postgres-shutdown"]

[tasks.udeps]
run = "cargo +nightly udeps --all-targets"

[tasks.lint]
run = [
    { task = "fmt" },
    { task = "db-postgres-init" },
    { task = "db-postgres-shutdown" },
    { task = "check" },
    { task = "clippy" },
    { task = "udeps" },
]

[tasks.ci]
depends = ["audit", "lint"]
# this is the only way to run a bunch of dependencies blocking and in order
run = """
#! /usr/bin/env bash
set -eo pipefail
trap 'mise run db-postgres-shutdown' EXIT
mise run db-postgres-init && mise run coverage && mise run build -- --release --locked
"""

